----
title: "Flavors"
date: 2018-11-12
----
author: duvany10
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Our backery
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
